function rayleighchan = createRayleighChannel(pathDelays,avgPathGains,dopplerShift,sampleRate)

rayleighchan = comm.RayleighChannel('SampleRate',sampleRate, ...
    'PathDelays',pathDelays/1e6, ...
    'AveragePathGains',avgPathGains, ...
    'MaximumDopplerShift',dopplerShift);
